/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kuan_com_myapplication_EventReader */

#ifndef _Included_kuan_com_myapplication_EventReader
#define _Included_kuan_com_myapplication_EventReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kuan_com_myapplication_EventReader
 * Method:    getEventFromInput
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kuan_com_myapplication_EventReader_getEventFromInput
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_kuan_com_myapplication_EventReader_showEvent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
